import { query } from './pool.js';

/**
 * Schema bootstrap.
 *
 * Idempotent DDL run at startup, which is the right weight for a single-service
 * app with one deployment target. The moment a column needs to change shape
 * under live data, this should become versioned migration files instead.
 *
 * `gen_random_uuid()` is core Postgres from 13 onwards, so ids are generated by
 * the database rather than the application.
 */
const DDL = `
CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL UNIQUE,
  name          text,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS urls (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  short_code   text NOT NULL UNIQUE,
  original_url text NOT NULL,
  expires_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Covers the dashboard listing: owner's rows, newest first.
CREATE INDEX IF NOT EXISTS urls_user_id_created_at_idx ON urls (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS clicks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- ON DELETE CASCADE replaces the manual click cleanup the JSON store did by hand.
  url_id       uuid NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
  clicked_at   timestamptz NOT NULL DEFAULT now(),
  referrer     text,
  user_agent   text,
  visitor_hash text NOT NULL
);

CREATE INDEX IF NOT EXISTS clicks_url_id_idx ON clicks (url_id);
`;

export async function ensureSchema(): Promise<void> {
  await query(DDL);
}
